# Generated by Django 5.2.4 on 2025-08-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rtsp', 'RTSP'), ('mvs', 'MVS'), ('video_file', 'Video File'), ('image_dir', 'Image Dir')], help_text='视频流类型', max_length=20)),
                ('name', models.CharField(help_text='视频流名称', max_length=100)),
                ('ip', models.GenericIPAddressField(blank=True, help_text='视频流 IP', null=True)),
                ('address', models.CharField(help_text='视频流地址', max_length=500)),
                ('width', models.PositiveIntegerField(blank=True, help_text='视频宽度', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='视频高度', null=True)),
                ('fps', models.PositiveIntegerField(blank=True, help_text='采集帧率', null=True)),
                ('enabled', models.BooleanField(default=True, help_text='是否启用')),
                ('status', models.CharField(choices=[('disabled', '未启用'), ('normal', '正常'), ('abnormal', '异常')], default='disabled', help_text='运行状态', max_length=20)),
                ('status_message', models.TextField(blank=True, help_text='状态说明')),
                ('save_frames', models.BooleanField(default=False, help_text='是否保存帧为图片')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
