# Generated by Django 5.2.4 on 2025-08-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rtsp', 'RTSP'), ('rtmp', 'RTMP'), ('http', 'HTTP'), ('websocket', 'WebSocket')], default='rtsp', help_text='视频流的协议类型', max_length=10, verbose_name='流类型')),
                ('ip', models.GenericIPAddressField(help_text='视频流源的IP地址', verbose_name='IP地址')),
                ('address', models.URLField(help_text='完整的视频流URL地址', max_length=500, verbose_name='流地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '视频流',
                'verbose_name_plural': '视频流',
                'ordering': ['-created_at'],
            },
        ),
    ]
