# Generated by Django 5.2.4 on 2025-08-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rtsp', 'RTSP'), ('mvs', 'MVS'), ('video_file', 'Video File'), ('image_dir', 'Image Dir')], help_text='视频流类型', max_length=20)),
                ('name', models.CharField(help_text='视频流名称', max_length=100)),
                ('ip', models.GenericIPAddressField(blank=True, help_text='视频流 IP', null=True)),
                ('address', models.CharField(help_text='视频流地址', max_length=500)),
                ('width', models.PositiveIntegerField(blank=True, help_text='视频宽度', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='视频高度', null=True)),
                ('fps', models.PositiveIntegerField(blank=True, help_text='采集帧率', null=True)),
                ('enabled', models.BooleanField(default=True, help_text='是否启用')),
                ('status', models.CharField(choices=[('disabled', '未启用'), ('normal', '正常'), ('abnormal', '异常')], default='disabled', help_text='运行状态', max_length=20)),
                ('status_message', models.TextField(blank=True, help_text='状态说明')),
                ('save_frames', models.BooleanField(default=False, help_text='是否保存帧为图片')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_video_stream',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlgoBigParticleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_id', models.PositiveIntegerField(help_text='所属视频流ID')),
                ('stream_name', models.CharField(help_text='视频流名称（冗余保存）', max_length=100)),
                ('min_size', models.PositiveIntegerField(help_text='最小粒径（毫米）')),
                ('max_size', models.PositiveIntegerField(help_text='最大粒径（毫米）')),
                ('detected_at', models.DateTimeField(help_text='检测时间')),
                ('original_image_id', models.PositiveIntegerField(blank=True, help_text='原图OSS对象ID', null=True)),
                ('rendered_image_id', models.PositiveIntegerField(blank=True, help_text='渲染图OSS对象ID', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间')),
            ],
            options={
                'db_table': 'algo_big_particle_record',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['stream_id', 'detected_at'], name='algo_big_pa_stream__f26a30_idx'), models.Index(fields=['stream_name', 'detected_at'], name='algo_big_pa_stream__367b95_idx'), models.Index(fields=['detected_at'], name='algo_big_pa_detecte_e18663_idx'), models.Index(fields=['max_size'], name='algo_big_pa_max_siz_08697e_idx'), models.Index(fields=['detected_at', 'max_size'], name='algo_big_pa_detecte_ec61e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='OssObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='文件存储路径', max_length=500, unique=True)),
                ('file_name', models.CharField(blank=True, help_text='原始文件名（可选）', max_length=255, null=True)),
                ('content_type', models.CharField(help_text='文件MIME类型', max_length=100)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='删除时间，为空表示未删除', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
            ],
            options={
                'db_table': 'core_oss_object',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='core_oss_ob_created_4fe115_idx')],
            },
        ),
    ]
