# Generated by Django 5.2.4 on 2025-08-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videostream',
            name='type',
            field=models.CharField(choices=[('rtsp', 'RTSP'), ('mvs', 'MVS'), ('video_file', 'Video File'), ('image_dir', 'Image Dir')], help_text='视频流类型', max_length=20),
        ),
    ]
