# Generated by Django 5.2.4 on 2025-08-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostream',
            name='save_frames',
            field=models.BooleanField(default=False, help_text='是否保存帧为图片'),
        ),
    ]
