# Generated by Django 5.2.4 on 2025-08-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mvs', 'MVS'), ('video_file', 'Video File'), ('image_dir', 'Image Dir')], default='mvs', help_text='视频流类型', max_length=20)),
                ('ip', models.GenericIPAddressField(help_text='视频流 IP')),
                ('address', models.CharField(help_text='视频流地址', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Stream',
        ),
    ]
