# Generated by Django 5.2.4 on 2025-08-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_videostream_delete_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostream',
            name='fps',
            field=models.PositiveIntegerField(blank=True, help_text='帧率（每秒帧数）', null=True),
        ),
        migrations.AddField(
            model_name='videostream',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='视频高度（像素）', null=True),
        ),
        migrations.AddField(
            model_name='videostream',
            name='width',
            field=models.PositiveIntegerField(blank=True, help_text='视频宽度（像素）', null=True),
        ),
    ]
