# Generated by Django 5.2.4 on 2025-08-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_videostream_save_frames'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostream',
            name='name',
            field=models.CharField(default='未命名', help_text='视频流名称', max_length=100),
        ),
    ]
