# Generated by Django 5.2.4 on 2025-09-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_algoblacklist_algobigparticlerecord_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='ossobject',
            name='bucket',
            field=models.CharField(blank=True, help_text='存储桶', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ossobject',
            name='storage_type',
            field=models.CharField(choices=[('local', '本地'), ('oss', 'OSS')], default='local', help_text='存储类型', max_length=20),
        ),
        migrations.AlterField(
            model_name='ossobject',
            name='file_path',
            field=models.CharField(help_text='文件存储路径', max_length=500),
        ),
    ]
