# Generated by Django 5.2.4 on 2025-08-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_videostream_fps_videostream_height_videostream_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostream',
            name='actual_fps',
            field=models.PositiveIntegerField(blank=True, help_text='实际帧率', null=True),
        ),
        migrations.AlterField(
            model_name='videostream',
            name='fps',
            field=models.PositiveIntegerField(blank=True, help_text='采集帧率', null=True),
        ),
        migrations.AlterField(
            model_name='videostream',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='视频高度', null=True),
        ),
        migrations.AlterField(
            model_name='videostream',
            name='width',
            field=models.PositiveIntegerField(blank=True, help_text='视频宽度', null=True),
        ),
    ]
