# Generated by Django 5.2.4 on 2025-08-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_videostream_actual_fps_alter_videostream_fps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostream',
            name='enabled',
            field=models.BooleanField(default=True, help_text='是否启用视频流'),
        ),
    ]
