# Generated by Django 5.2.4 on 2025-09-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ossobject_bucket_ossobject_storage_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgoBigParticleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_id', models.PositiveIntegerField(help_text='所属视频流ID')),
                ('stream_name', models.CharField(help_text='视频流名称（冗余保存）', max_length=100)),
                ('size', models.PositiveIntegerField(help_text='粒径尺寸（毫米）')),
                ('record_id', models.PositiveIntegerField(help_text='算法记录ID')),
                ('instance', models.JSONField(help_text='检测实例', null=True)),
                ('detected_at', models.DateTimeField(help_text='检测时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间')),
            ],
            options={
                'db_table': 'algo_big_particle_detail',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='algobigparticlerecord',
            new_name='core_algo_r_detecte_81c2f0_idx',
            old_name='algo_big_pa_detecte_2f10fb_idx',
        ),
        migrations.RenameIndex(
            model_name='algobigparticlerecord',
            new_name='core_algo_r_detecte_a18f4a_idx',
            old_name='algo_big_pa_detecte_464253_idx',
        ),
        migrations.RenameIndex(
            model_name='algobigparticlerecord',
            new_name='core_algo_r_detecte_5375c6_idx',
            old_name='algo_big_pa_detecte_ec61e5_idx',
        ),
        migrations.AddField(
            model_name='algobigparticlerecord',
            name='algo_name',
            field=models.CharField(default='big_particle', help_text='算法名称', max_length=100),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='algobigparticlerecord',
            index=models.Index(fields=['detected_at', 'algo_name'], name='core_algo_r_detecte_5338aa_idx'),
        ),
        migrations.AlterModelTable(
            name='algobigparticlerecord',
            table='core_algo_record',
        ),
        migrations.AddIndex(
            model_name='algobigparticledetail',
            index=models.Index(fields=['detected_at', 'stream_id'], name='algo_big_pa_detecte_e3acf3_idx'),
        ),
        migrations.AddIndex(
            model_name='algobigparticledetail',
            index=models.Index(fields=['detected_at', 'stream_name'], name='algo_big_pa_detecte_409a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='algobigparticledetail',
            index=models.Index(fields=['detected_at', 'size'], name='algo_big_pa_detecte_aaa8e2_idx'),
        ),
        migrations.AddIndex(
            model_name='algobigparticledetail',
            index=models.Index(fields=['record_id'], name='algo_big_pa_record__acee30_idx'),
        ),
    ]
