# Generated by Django 5.2.4 on 2025-08-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_videostream_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videostream',
            name='address',
            field=models.CharField(blank=True, help_text='视频流地址', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='videostream',
            name='enabled',
            field=models.BooleanField(default=True, help_text='是否启用'),
        ),
        migrations.AlterField(
            model_name='videostream',
            name='ip',
            field=models.GenericIPAddressField(blank=True, help_text='视频流 IP', null=True),
        ),
    ]
