# 修复后的迁移文件
# Generated by Django 5.2.4 on 2025-09-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_algobigparticledetail_and_more'),
    ]

    operations = [
        # 重命名模型
        migrations.RenameModel(
            old_name='AlgoBigParticleRecord',
            new_name='AlgoRecord',
        ),
        # 删除包含 max_size 字段的索引（必须在删除字段之前）
        migrations.RemoveIndex(
            model_name='algorecord',
            name='core_algo_r_detecte_5375c6_idx',  # ['detected_at', 'max_size'] 索引
        ),
        # 删除 min_size 字段
        migrations.RemoveField(
            model_name='algorecord',
            name='min_size',
        ),
        # 删除 max_size 字段
        migrations.RemoveField(
            model_name='algorecord',
            name='max_size',
        ),
    ]