# Generated by Django 5.2.4 on 2025-09-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_algorecord_delete_min_max_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='状态键名', max_length=100, unique=True)),
                ('value', models.JSONField(help_text='状态值')),
                ('description', models.TextField(blank=True, help_text='状态描述')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
            ],
            options={
                'db_table': 'core_system_state',
            },
        ),
    ]
