# Generated by Django 5.2.4 on 2025-09-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_systemstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_type', models.CharField(help_text='告警类型', max_length=50)),
                ('stream_id', models.PositiveIntegerField(blank=True, help_text='关联的视频流ID', null=True)),
                ('stream_name', models.CharField(blank=True, help_text='视频流名称（冗余保存）', max_length=100)),
                ('data', models.JSONField(help_text='告警数据（JSON格式）')),
                ('alarm_time', models.DateTimeField(help_text='告警时间')),
                ('record_id', models.PositiveIntegerField(blank=True, help_text='关联的记录ID', null=True)),
                ('alarm_image_id', models.PositiveIntegerField(blank=True, help_text='告警图OSS对象ID', null=True)),
                ('original_image_id', models.PositiveIntegerField(blank=True, help_text='原图OSS对象ID', null=True)),
                ('alarm_video_id', models.PositiveIntegerField(blank=True, help_text='告警视频OSS对象ID', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录更新时间')),
            ],
            options={
                'db_table': 'core_alarm',
                'ordering': ['-alarm_time'],
                'indexes': [models.Index(fields=['alarm_time', 'alarm_type'], name='core_alarm_alarm_t_938e08_idx'), models.Index(fields=['alarm_time', 'stream_id'], name='core_alarm_alarm_t_5821e8_idx')],
            },
        ),
    ]
