# netdata can generate its own config which is available at 'http://<IP>:19999/netdata.conf'
# You can download it using:
#    curl -o //etc/netdata/netdata.conf http://localhost:19999/netdata.conf
# or
#    wget -O //etc/netdata/netdata.conf http://localhost:19999/netdata.conf

[db]
    dbengine tier 0 retention time = 14d
    dbengine tier 0 retention size = 5GiB

    dbengine tier 1 retention time = 3mo
    dbengine tier 1 retention size = 5GiB

    dbengine tier 2 retention time = 1y
    dbengine tier 2 retention size = 5GiB
