{
 "title": "engine",
 "description": "引擎运行信息",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(engine_stream_status,instance)"
    }
   },
   {
    "name": "gpu",
    "query": {
     "query": "label_values(engine_stream_status{instance=~\"$instance\"},gpu)"
    }
   },
   {
    "name": "cameraId",
    "query": {
     "query": "label_values(engine_stream_status{instance=~\"$instance\"},cameraId)"
    }
   },
   {
    "name": "model",
    "query": {
     "query": "label_values(engine_ability_process_timer_seconds_count{instance=~\"$instance\"},model)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "流总数",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(engine_stream_status{instance=~\"$instance\", gpu=~\"$gpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "流有效数",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(engine_stream_status{instance=~\"$instance\", gpu=~\"$gpu\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "流无效数",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(engine_stream_status{instance=~\"$instance\", gpu=~\"$gpu\"} == -1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "观看者数量",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(engine_receiver_count{instance=~\"$instance\", gpu=~\"$gpu\", cameraId=~\"$cameraId\"})",
     "legendFormat": "观看者数量"
    }
   ]
  },
  {
   "title": "流数量",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count_values(\"status\", engine_stream_status{instance=~\"$instance\", gpu=~\"$gpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "流状态",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "engine_stream_status{instance=~\"$instance\", gpu=~\"$gpu\", cameraId=~\"$cameraId\"}",
     "legendFormat": "{{cameraId}}"
    }
   ]
  },
  {
   "title": "丢帧统计",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "rate(engine_decoder_drop_counter_total{instance=~\"$instance\", gpu=~\"$gpu\", cameraId=~\"$cameraId\"}[$__rate_interval])",
     "legendFormat": "解码丢帧-{{cameraId}}"
    },
    {
     "expr": "rate(engine_infer_drop_counter_total{instance=~\"$instance\", gpu=~\"$gpu\", cameraId=~\"$cameraId\"}[$__rate_interval])",
     "legendFormat": "推理丢帧-{{cameraId}}"
    },
    {
     "expr": "rate(engine_encoder_drop_counter_total{instance=~\"$instance\", gpu=~\"$gpu\", cameraId=~\"$cameraId\"}[$__rate_interval])",
     "legendFormat": "编码丢帧-{{cameraId}}"
    },
    {
     "expr": "rate(engine_encoder_ahead_counter_total{instance=~\"$instance\", gpu=~\"$gpu\", cameraId=~\"$cameraId\"}[$__rate_interval])",
     "legendFormat": "推理超时-{{cameraId}}"
    }
   ]
  },
  {
   "title": "编解码次数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(engine_decoder_timer_seconds_count{instance=~\"$instance\", gpu=~\"$gpu\", cameraId=~\"$cameraId\"}[$__rate_interval])",
     "legendFormat": "解码次数-{{cameraId}}"
    },
    {
     "expr": "rate(engine_encoder_timer_seconds_count{instance=~\"$instance\", gpu=~\"$gpu\", cameraId=~\"$cameraId\"}[$__rate_interval])",
     "legendFormat": "编码次数-{{cameraId}}"
    }
   ]
  },
  {
   "title": "编解码耗时",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(rate(engine_decoder_timer_seconds_sum{instance=~\"$instance\", gpu=~\"$gpu\", cameraId=~\"$cameraId\"}[$__rate_interval]) * 1000) / rate(engine_decoder_timer_seconds_count{instance=~\"$instance\", gpu=~\"$gpu\", cameraId=~\"$cameraId\"}[$__rate_interval])",
     "legendFormat": "解码耗时-{{cameraId}}"
    },
    {
     "expr": "(rate(engine_encoder_timer_seconds_sum{instance=~\"$instance\", gpu=~\"$gpu\", cameraId=~\"$cameraId\"}[$__rate_interval]) * 1000) / rate(engine_encoder_timer_seconds_count{instance=~\"$instance\", gpu=~\"$gpu\", cameraId=~\"$cameraId\"}[$__rate_interval])",
     "legendFormat": "编码耗时-{{cameraId}}"
    }
   ]
  },
  {
   "title": "推理次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(engine_ability_process_timer_seconds_count{instance=~\"$instance\", gpu=~\"$gpu\", model=~\"$model\"}[$__rate_interval])",
     "legendFormat": "推理次数-{{model}}"
    }
   ]
  },
  {
   "title": "推理耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "engine_ability_process_timer_seconds{instance=~\"$instance\", gpu=~\"$gpu\", model=~\"$model\"} * 1000",
     "legendFormat": "推理耗时-{{model}}-{{quantile}}"
    },
    {
     "expr": "(rate(engine_ability_process_timer_seconds_sum{instance=~\"$instance\", gpu=~\"$gpu\", model=~\"$model\"}[$__rate_interval]) * 1000) / rate(engine_ability_process_timer_seconds_count{instance=~\"$instance\", gpu=~\"$gpu\", model=~\"$model\"}[$__rate_interval])",
     "legendFormat": "推理耗时-{{model}}-avg"
    }
   ]
  }
 ]
}