# Generated by Django 5.2.4 on 2025-08-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_type', models.CharField(help_text='配置类型', max_length=50)),
                ('name', models.CharField(help_text='配置名称', max_length=100)),
                ('description', models.TextField(blank=True, help_text='配置说明')),
                ('config_data', models.JSONField(default=dict, help_text='配置数据（JSON格式）')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
            ],
            options={
                'db_table': 'core_system_config',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('config_type', 'name'), name='unique_config_type_name')],
            },
        ),
    ]
