# Generated by Django 5.2.4 on 2025-09-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='algobigparticledetail',
            name='long_size',
            field=models.PositiveIntegerField(help_text='长边尺寸（毫米）', null=True),
        ),
        migrations.AddField(
            model_name='algobigparticledetail',
            name='short_size',
            field=models.PositiveIntegerField(help_text='短边尺寸（毫米）', null=True),
        ),
    ]
